### ISSUE TITLE
haproxy-1.5.12 test suite badly broken + fixes required for successful test run

### ISSUE THREAD

**Issue by davidfavor** [observing/haproxy#12]
Summary of fixes, for tests to run correctly...

- extend haproxy npm module dependencies to include mocha + chai + sinon-chai

- package.json is incorrect + find should change from 'test' to 'node_modules'

- package.json is incorrectly placed, so ln -s node_modules/haproxy/package.json . is required.

Seems like entire test suite may have evolved organically +  requires to be run inside a pristine build environment (where npm has never been installed + no npm modules have been installed), so entire test flow can be fixed.
_______

Detailed list of problems + resolutions.

1) npm install haproxy --save - produces this error message...

npm ERR! not a package /tmp/npm-29229-1Lj84CuY/1432732957086-0.35323801008053124/tmp.tgz

fix: unsure

workaround: cd / && npm --prefix=$(pwd) install haproxy --save

2) mocha isn't defined as a dependency.

fix: define mocha as dependency, along with which + dsv + mkdirp

workaround: npm install mocha --save

3) npm test - first breakage.

net8-rmt# npm test
npm ERR! Error: ENOENT, open '/buildstacks/work/haproxy-1.5.12/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-18-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "test"
npm ERR! cwd /buildstacks/work/haproxy-1.5.12
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /buildstacks/work/haproxy-1.5.12/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /buildstacks/work/haproxy-1.5.12/npm-debug.log
npm ERR! not ok code 0

Failed because package.json is the wrong place.

workaround: ln -s node_modules/haproxy/package.json .

4) npm test - 2nd breakage

net8-rmt# npm test

> haproxy@0.1.0 test /buildstacks/work/haproxy-1.5.12
> NODE_ENV=testing ./node_modules/.bin/mocha $(find test -name '*.test.js')

find: `test': No such file or directory

/buildstacks/work/haproxy-1.5.12/node_modules/mocha/lib/utils.js:591
      if (!files.length) throw new Error("cannot resolve path (or pattern) '" 
                               ^
Error: cannot resolve path (or pattern) 'test'
    at Object.lookupFiles (/buildstacks/work/haproxy-1.5.12/node_modules/mocha/lib/utils.js:591:32)
    at runAgain (/buildstacks/work/haproxy-1.5.12/node_modules/mocha/bin/_mocha:320:30)
    at Array.forEach (native)
    at Object.<anonymous> (/buildstacks/work/haproxy-1.5.12/node_modules/mocha/bin/_mocha:319:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

There is no 'test' directory. Maybe this should be 'node_modules'.

5) npm test - 3rd breakage

net8-rmt# npm test

> haproxy@0.1.0 test /buildstacks/work/haproxy-1.5.12
> NODE_ENV=testing ./node_modules/.bin/mocha $(find node_modules -name '*.test.js')

module.js:340
    throw err;
          ^
Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Suite.<anonymous> (/buildstacks/work/haproxy-1.5.12/node_modules/haproxy/test/haproxy.test.js:7:14)
    at context.describe.context.context (/buildstacks/work/haproxy-1.5.12/node_modules/mocha/lib/interfaces/bdd.js:49:10)
    at Object.<anonymous> (/buildstacks/work/haproxy-1.5.12/node_modules/haproxy/test/haproxy.test.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /buildstacks/work/haproxy-1.5.12/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/buildstacks/work/haproxy-1.5.12/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/buildstacks/work/haproxy-1.5.12/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/buildstacks/work/haproxy-1.5.12/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

Now chai is missing.

fix/workaround: change 'test' to 'node_modules' in package_json

fix: define chai as a dependency

workaround: npm install chai --save

6) npm test - 4th breakage

Dependency sinon-chai missing.

fix: define sinon-chai as a dependency

workaround: npm install sinon-chai --save

**Comment by davidfavor** [comment]
Here's the compacted steps from my auto build process.

cd / && npm --prefix=$pkgdir install haproxy mocha chai sinon-chai --save
ln -sf node_modules/haproxy/package.json .
perl -pi -e 's/find test/find node_modules/g' package.json
npm test

Which results in 100% test suite running with success.

**Comment by davidfavor** [comment]
Also suggest test suite use a different port than 8080, as this is a commonly used port + test suite will fail if this port is bound.

In fact, best way to do this is to test open a port, till a free port is found.

**Comment by 3rd-Eden** [comment]
Not sure what causes your issues as things like `chai` are defined in the devDependencies as they shoud; https://github.com/observing/haproxy/blob/master/package.json#L16 and should *not* be installed as dependency as it's only required for running the test script, which isn't done when you run `npm install haproxy`. 

I do agree that some parts like the test script could be improved to something like: 

```
"NODE_ENV=testing mocha $(find test -name '*.test.js')
```

As npm is smart enough to find `mocha` in the node_modules folder. But these are all side affects from a really odd setup you got going here.

**Comment by Swaagie** [comment]
I'll try to be as extensive as possible, hopefully this will give you some directions. 

1) `npm install haproxy` works fine for me, might be an npm cache issue

![screen shot 2015-05-28 at 17 49 32](https://cloud.githubusercontent.com/assets/670951/7864384/f2529abe-0561-11e5-9ca8-f89df6fd8bc7.png)

2) mocha, chai etc are all defined in [package.json just fine](https://github.com/observing/haproxy/blob/master/package.json#L11-L18), you might have installed with `NODE_ENV=production` and thereby omitting the devDependencies.

3) `/buildstacks/work/haproxy-1.5.12/package.json` seems like the working directory of haproxy itself. Tests have to be run from inside the haproxy module directory, your mixing the two here. I think this also explains 4 and 5. 

I think the main issue here is mixing up this node.js config/bridging module with the actual haproxy instance http://www.haproxy.org/

In general test directions can be found here: https://github.com/observing/haproxy#testing

**Comment by davidfavor** [comment]
Very simple setup.

1) Install fresh Ubuntu Vivid

2) Login as root

3) Run haproxy build procedure

**Comment by davidfavor** [comment]
So you say "Tests have to be run from inside the haproxy module directory".

Does this mean the directory where haproxy is installed?

So in my case, /stacks/ubuntu-15.04-vivid/drf-lamp-2015-05?

If so, there is no node_modules directory in the install directory.

Maybe - cd $PREFIX - is required before the npm test step?

**Comment by davidfavor** [comment]
Nope.

 cd $PREFIX && npm install haproxy --save && npm test

also fails, in same way.

**Comment by davidfavor** [comment]
I think what might be better is for the documentation to show every step of test sequence.

Each command, using $PREFIX where required.

**Comment by Swaagie** [comment]
I'll extend the test directives to exactly explain what to do

**Comment by Swaagie** [comment]
Fyi: work in progress is in https://github.com/observing/haproxy/tree/debt, what node version where you testing with btw? 0.12 def has some issues.

**Comment by davidfavor** [comment]
Thanks for extending the directives.

Node I'm using is stock Ubuntu Vivid version.

node net8-rmt# node --version
v0.10.25

I'll give the instructions above a try + see how it goes.

Thanks.

**Comment by Swaagie** [comment]
The instructions are not complete yet, afraid I can't work fulltime on
this. I'll keep you informed when I'm done
Op 29 mei 2015 2:48 PM schreef "David Favor" <notifications@github.com>:

**Comment by Swaagie** [comment]
Done with updates, test running properly with most node version now, test directives should be more detailed now https://travis-ci.org/observing/haproxy/builds/64707708

**Comment by Swaagie** [comment]
PR is here, @3rd-Eden can review, merge and pull it in

**Comment by Swaagie** [comment]
Released as 0.2.0
